# Generated by Django 4.2.4 on 2023-08-14 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_registrotareas_fecha_vencimiento_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='fecha_vencimiento_tarea',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha vencimiento tarea (dd-mm-yyyy)'),
        ),
    ]
