# Generated by Django 4.2.4 on 2023-08-14 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_alter_registrotareas_fecha_vencimiento_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='fecha_vencimiento_tarea',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 2, 16, 47, 125060, tzinfo=datetime.timezone.utc), verbose_name='Fecha vencimiento tarea (dd-mm-yyyy)'),
        ),
    ]
